import fsp from 'fs/promises';
import path from 'path';

import mustache from 'mustache';

import { execCmd } from './execCmd';
import { examples } from '../src/parseArgs';

const templateFilename = path.join(__dirname, 'template.md');
const rootDir = path.join(__dirname, '..');
const readmeFilename = path.join(__dirname, '..', 'README.md');
const examplesFilename = path.join(__dirname, 'examples.bat');

const curlData = {
    curlDemo0: `curl -L https://github.com/metamath/set.mm/raw/refs/heads/develop/demo0.mm -O`,
    curlSetMm: `curl -L https://github.com/metamath/set.mm/raw/refs/heads/develop/set.mm -O`,
};

const namedCommands = [
    ['helpMain', 'npm start -- --help'],
    ['helpGet', 'npm start -- --help get'],
    ['helpUnify', 'npm start -- --help unify'],
    ['helpCompress', 'npm start -- --help compress'],
    ['helpDecompress', 'npm start -- --help decompress'],
    ['helpTruncate', 'npm start -- --help truncate'],
];

const main = async () => {
    const template = await fsp.readFile(templateFilename, {
        encoding: 'utf-8',
    });

    const helpData = await Promise.all(
        namedCommands.map(async ([name, cmd]) => {
            const data = await execCmd(cmd, { cwd: rootDir });
            return [
                name,
                data
                    .split('\n')
                    .filter((s) => !s.startsWith('> '))
                    .join('\n')
                    .trim(),
            ];
        }),
    );

    const data = { ...curlData, ...Object.fromEntries(helpData) };

    const readme = mustache.render(template, data);
    await fsp.writeFile(readmeFilename, readme);

    const callPrefix = (s: string) => [``, `@echo on`, `call ${s}`].join('\n');

    const checkmmSuffix = (s: string) =>
        [s, callPrefix(`checkmm set.mm`)].join('\n');

    const exampleScript = [
        `@REM  * Auto-generated by doc.ts *`,
        `@REM  Assumes: npm install --global yamma checkmm`,
        ``,
        `@echo on`,
        curlData.curlDemo0 + ` --ssl-no-revoke`,
        callPrefix(`checkmm demo0.mm`),
        ``,
        `@echo on`,
        curlData.curlSetMm + ` --ssl-no-revoke`,
        callPrefix(`checkmm set.mm`),
        ...examples.get.map(callPrefix),
        ...examples.unify.map(callPrefix),
        ...examples.decompress.map(callPrefix),
        callPrefix(`checkmm demo0.mm`),
        callPrefix(`checkmm set.mm`),
        ...examples.compress.map(callPrefix),
        callPrefix(`checkmm demo0.mm`),
        callPrefix(`checkmm set.mm`),
        ...examples.truncate.map(callPrefix).map(checkmmSuffix),
    ].join('\n');

    await fsp.writeFile(examplesFilename, exampleScript);
};

main();
