@REM  * Auto-generated by doc.ts *
@REM  Assumes: npm install --global yamma checkmm

@echo on
curl -L https://github.com/metamath/set.mm/raw/refs/heads/develop/demo0.mm -O --ssl-no-revoke

@echo on
call checkmm demo0.mm

@echo on
curl -L https://github.com/metamath/set.mm/raw/refs/heads/develop/set.mm -O --ssl-no-revoke

@echo on
call checkmm set.mm

@echo on
call yamma get demo0.mm th1

@echo on
call yamma get set.mm impt dju1p1e2

@echo on
call yamma unify demo0.mm th1.mmp

@echo on
call yamma unify set.mm impt.mmp dju1p1e2.mmp

@echo on
call yamma decompress demo0.mm th1

@echo on
call yamma decompress set.mm impt dju1p1e2

@echo on
call checkmm demo0.mm

@echo on
call checkmm set.mm

@echo on
call yamma compress demo0.mm th1

@echo on
call yamma compress set.mm impt dju1p1e2

@echo on
call checkmm demo0.mm

@echo on
call checkmm set.mm

@echo on
call yamma truncate set.mm --before dju1p1e2

@echo on
call checkmm set.mm

@echo on
call yamma truncate set.mm --after impt

@echo on
call checkmm set.mm

@echo on
call yamma truncate set.mm --count 100

@echo on
call checkmm set.mm